language: rust
rust:
  - 1.6.0
  - 1.7.0
  - 1.8.0
  - 1.9.0
  - 1.10.0
  - 1.11.0
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc

# Use Travis container-based infrastructure
sudo: false

# Send notifications to homu bot
notifications:
    webhooks: http://rust-embedded-bot.herokuapp.com/travis

branches:
  only:
    - auto
